# Generated by Django 5.2.15 on 2026-08-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requires_manual_review',
            field=models.BooleanField(default=False),
        ),
    ]
