# Generated by Django 5.2.15 on 2026-08-05 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_failed_login_attempts_user_locked_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILURE', 'Login Failure'), ('LOGIN_LOCKOUT', 'Login Lockout'), ('LOGOUT', 'Logout'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('EMAIL_VERIFICATION_REQUESTED', 'Email Verification Requested'), ('EMAIL_VERIFIED', 'Email Verified'), ('EMAIL_OTP_FAILED', 'Email OTP Failed'), ('EMAIL_OTP_LOCKED', 'Email OTP Locked'), ('TOKEN_REFRESH', 'Token Refresh'), ('TOKEN_BLACKLISTED', 'Token Blacklisted')], db_index=True, max_length=64)),
                ('email', models.CharField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='authenticat_event_t_1133f1_idx'), models.Index(fields=['user', 'created_at'], name='authenticat_user_id_01c307_idx')],
            },
        ),
    ]
